# workshop-template https://github.com/evanwill/workshop-template
# A Jekyll template for a simple workshop website, designed for github-pages,
# based on Minima theme https://github.com/jekyll/minima

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: I Curso de Escrita Acadêmica com LaTeX - Programa de Pós-Graduação em Letras - UFOP - 2019
description: "Curso introdutório de LaTeX para escrita de artigos, apresentações, dissertações e teses."
keywords: "latex, latex-ufop, pos-letras ufop, ppgl-ufop"

# author settings for cc-by
author: Danny Tonidandel
pub_year: 2019
github_username: tonidandel
# add the full url for the github repository
repo: "https://github.com/tonidandel/oficina-latex-pos-letras-2019"

# urls
# your gh-pages url: https://username.github.io
url: https://tonidandel.github.io/
# your repository name: /ghpages-test-site
baseurl: /oficina-latex-pos-letras-2019
# analytics if desired (and use environment variable on build command)
#google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
